apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-pod
spec:
  containers:
    - name: ubuntu-sleeper
      image: ubuntu-sleeper
      command: ["sleep-2.0"] # <- Overwriting the command instruction in the docker file
      args: ["10"] # <- Arguments to send to the image
