---
apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: feuna3nU81WyqeNHhZczUnKQsTj7I1coHTZbn/CmJek=
      - identity:
          {} # this fallback allows reading unencrypted secrets;
          # for example, during initial migration
